### ISSUE TITLE
Lab Creator tool should have a method of saving the output

### ISSUE THREAD

**Issue by RogerBestMsft** [Azure/LabServices#2]
Ideally - this should be covered with PowerShell's transcript functionality, if that works we should add instructions to the readme so users know exactly what to do.
Moved from https://github.com/Azure/azure-devtestlab/issues/743

**Comment by EMaher** [comment]
Can use existing PowerShell cmdlets to save transcript. [Start-Transcript](https://learn.microsoft.com/powershell/module/microsoft.powershell.host/start-transcript) and [Stop-Transcript](https://learn.microsoft.com/powershell/module/microsoft.powershell.host/stop-transcript).
