### ISSUE TITLE
Investigate script support for Ubuntu 23.04

### ISSUE THREAD

**Issue by nicolehaugen** [Azure/LabServices#34]
Currently the Linux scripts haven't been thoroughly tested for Ubuntu 23.04.  This needs to be investigated further, because Ubuntu 23.04 may require a GPU.  Azure Labs doesn't currently have a VM size that support GPU Visualization for Linux.  Also, I have *not* been able to get Ubuntu 23.04 to be successfully installed on a non-GPU size.

We should confirm the steps to install on Ubuntu 23.04 directly on an Azure VM GPU sku to validate that Ubuntu 23.04 can be configured properly, and then follow up accordingly.

**Comment by EMaher** [comment]
Will reopen if we receive a request from the community.
